# Generated by Django 4.2.7 on 2025-11-12 23:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Association",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField(blank=True)),
                (
                    "management_company",
                    models.CharField(default="Dynamite Management", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SpecialAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., '2024 Special Assessment'", max_length=200
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "total_loan_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Total loan amount", max_digits=12
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annual interest rate percentage",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "loan_period_months",
                    models.IntegerField(help_text="Number of months for the loan"),
                ),
                (
                    "monthly_loan_payment",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Association's monthly loan payment",
                        max_digits=12,
                    ),
                ),
                ("start_date", models.DateField(help_text="First payment due date")),
                (
                    "total_base_assessment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_lce_assessments",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total Limited Common Element assessments",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "association",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_assessments",
                        to="assessments.association",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_number",
                    models.CharField(
                        help_text="Unit number (e.g., A1, B9, L51)", max_length=50
                    ),
                ),
                ("owner_name", models.CharField(blank=True, max_length=200)),
                ("owner_email", models.EmailField(blank=True, max_length=254)),
                ("owner_phone", models.CharField(blank=True, max_length=20)),
                (
                    "common_expense_allocation",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Percentage of common expenses (typically 1% for 100 units)",
                        max_digits=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "association",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="assessments.association",
                    ),
                ),
            ],
            options={
                "ordering": ["unit_number"],
                "unique_together": {("association", "unit_number")},
            },
        ),
        migrations.CreateModel(
            name="UnitAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_assessment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Base assessment amount",
                        max_digits=12,
                    ),
                ),
                (
                    "payment_option",
                    models.CharField(
                        choices=[("lump", "Lump Sum"), ("monthly", "Monthly Payments")],
                        default="monthly",
                        max_length=10,
                    ),
                ),
                (
                    "monthly_base_payment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Monthly payment for base assessment with interest",
                        max_digits=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "special_assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unit_assessments",
                        to="assessments.specialassessment",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unit_assessments",
                        to="assessments.unit",
                    ),
                ),
            ],
            options={
                "ordering": ["unit__unit_number"],
                "unique_together": {("unit", "special_assessment")},
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_date", models.DateField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'Check', 'Wire', 'ACH'",
                        max_length=50,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="Check number or transaction reference",
                        max_length=100,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "unit_assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="assessments.unitassessment",
                    ),
                ),
            ],
            options={
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="AdditionalFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fee_type",
                    models.CharField(
                        help_text="e.g., 'Deck', 'Skylight', 'Special Item'",
                        max_length=100,
                    ),
                ),
                (
                    "fee_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Additional fee amount",
                        max_digits=12,
                    ),
                ),
                (
                    "monthly_payment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Monthly payment for this fee with interest",
                        max_digits=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "unit_assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_fees",
                        to="assessments.unitassessment",
                    ),
                ),
            ],
        ),
    ]
