# Generated by Django 4.2.7 on 2025-11-13 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(help_text='Payment due date (1st of each month)')),
                ('month_number', models.IntegerField(help_text='Month number (1-240)')),
                ('expected_amount', models.DecimalField(decimal_places=2, help_text='Expected payment amount for this month', max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount paid for this month', max_digits=10)),
                ('paid_date', models.DateField(blank=True, help_text='Date payment was received', null=True)),
                ('payment_method', models.CharField(blank=True, help_text="e.g., 'Check', 'Wire', 'ACH'", max_length=50)),
                ('reference_number', models.CharField(blank=True, help_text='Check number or transaction reference', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_schedule', to='assessments.unitassessment')),
            ],
            options={
                'ordering': ['due_date'],
                'unique_together': {('unit_assessment', 'month_number')},
            },
        ),
    ]
