# Generated by Django 4.2.7 on 2025-11-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_monthlypaymentschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitassessment',
            name='is_paid_off',
            field=models.BooleanField(default=False, help_text='Whether assessment has been paid off'),
        ),
        migrations.AddField(
            model_name='unitassessment',
            name='payoff_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Lump sum payoff amount paid', max_digits=12),
        ),
        migrations.AddField(
            model_name='unitassessment',
            name='payoff_date',
            field=models.DateField(blank=True, help_text='Date of payoff payment', null=True),
        ),
    ]
